version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  backend:
    build: ./backend
    container_name: ecommerce_backend
    restart: always
    ports:
      - "5050:5050"
    environment:
      DATABASE_URL: postgres://admin:supersecretpassword@db:5432/ecommerce
      PORT: 5050
    depends_on:
      - db
    networks:
      - ecommerce_net

  frontend:
    build: ./frontend
    container_name: ecommerce_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ecommerce_net

volumes:
  pgdata:

networks:
  ecommerce_net:
    driver: bridge
